updated by piyush

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -38,14 +38,14 @@ jobs:
             ${{ runner.os }}-maven-
 
       - name: Run TestNG tests
-        run: |
-          case "${{ github.event.inputs.module }}" in
-            SCS) mvn test -DsuiteXmlFile=testngscs.xml ;;
-            DM) mvn test -DsuiteXmlFile=testngDoublemateriality.xml ;;
-            ESRSLITE) mvn test -DsuiteXmlFile=testngESRSLITE.xml ;;
-			EU) mvn test -DsuiteXmlFile=testngEU.xml ;;
-            *) echo "Invalid module name"; exit 1 ;;
-          esac
+	  run: |
+	      case '${{ github.event.inputs.module }}' in
+	        SCS) mvn test -DsuiteXmlFile=testngscs.xml ;;
+	        DM) mvn test -DsuiteXmlFile=testngDoublemateriality.xml ;;
+	        ESRSLITE) mvn test -DsuiteXmlFile=testngESRSLITE.xml ;;
+	        EU) mvn test -DsuiteXmlFile=testngEU.xml ;;
+	        *) echo "Invalid module name: ${{ github.event.inputs.module }}"; exit 1 ;;
+	      esac
 
       - name: Convert TestNG Results to JSON
         if: always()
